name: Deploy to EC2
on:
    push:
        branches:
           - main


jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checking out code on runner
              uses: actions/checkout@v4  #plugin version

            - name: Login and update EC2 instance
              uses: appleboy/ssh-action@v1.0.0
              with:
                      host: ${{ secrets.EC2_HOST }}
                      username: ${{ secrets.EC2_USERNAME }}
                      password: ${{ secrets.EC2_SSH_KEY }}
                      port: 22
                      script: |
                             pwd
                             whoami
                             sudo apt-get update -y
          
