name: Deploying to EC2
on:
    push:
        branches:
           -main


jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Print  my name
              run: |
                  echo "Nikhil"
                  
            - name:  Current folder
              run: |
                  pwd
          
